import os
import sys
from datetime import date
from pathlib import Path

import pycfast

sys.path.insert(0, os.path.abspath("../../src"))

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "PyCFAST"
author = pycfast.__author__
copyright = f"{date.today().year}" # complete copyright with pycfast_footer.html to include link
version = pycfast.__version__
print(f"Building documentation for version {version}")

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autosummary",
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx_copybutton",
    "sphinx_autodoc_typehints",
    "myst_parser",  # markdown support (MyST)
    "sphinx_gallery.gen_gallery",
]
autosummary_generate = True
autodoc_default_options = {"members": False, "undoc-members": False, "inherited-members": True}
toc_object_entries_show_parents = "hide"

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "html_admonition",
    "html_image",
    "linkify",  # Re-enabled with linkify-it-py dependency
    "replacements",
    "smartquotes",
    "substitution",
    "tasklist",
]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# NumPy docstrings behavior
napoleon_numpy_docstring = True
napoleon_google_docstring = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_include_init_with_doc = True

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "logos/lsapy/branding.md"]

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output
html_title = "PyCFAST"
html_static_path = ["_static"]
templates_path = ["_templates"]

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "pydata_sphinx_theme"

html_theme_options = {
    "icon_links": [
        {"name": "GitHub", "url": "https://github.com/bewygs/pycfast", "icon": "fa-brands fa-github"}
        ],
    "article_footer_items": [],
    "show_prev_next": True,
    "navigation_with_keys": True,
    "show_toc_level": 2,
    "footer_start": ["pycfast_footer", "sphinx-version"],
    "footer_end": ["theme-version"],
    "switcher": {
        "json_url": "_static/version.json",
        "version_match": version,
    },
    "navbar_start": ["navbar-logo", "version-switcher"],
    "navbar_end": ["theme-switcher", "navbar-icon-links"],
    "secondary_sidebar_items": ["page-toc", "edit-this-page", "sourcelink"],
}

html_sidebars = {
    "installation": [],
    "getting_started": [],
    "examples/*": [],
    "contributing": [],
    "changelog": [],
    "acknowledgments": [],
    "licence": [],
    "citation": [],
}

# -- Intersphinx (with cross-links) ------------------------------------------
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
}


sphinx_gallery_conf = {
    "examples_dirs": "../../examples",
    "gallery_dirs": "auto_examples",
    # "subsection_order": "alphabetical",
    "within_subsection_order": "FileNameSortKey"
}
