from __future__ import annotations

import glob
import os
from pathlib import Path

import pytest
from csv_comparison import (
    compare_model_to_reference_data,
    get_reference_data_dir,
)

from pycfast.parsers import parse_cfast_file


def get_all_validation_input_files():
    """Get all .in files from the validation test directories."""
    validation_dir = Path(__file__).parent / "Validation"
    return glob.glob(str(validation_dir / "**" / "*.in"), recursive=True)


def get_test_parameters():
    """Generate test parameters for all validation input files."""
    input_files = get_all_validation_input_files()
    test_params = []

    for input_file in input_files:
        file_path = Path(input_file)
        parent_dir = file_path.parent.name
        file_prefix = file_path.stem
        test_params.append((input_file, parent_dir, file_prefix))

    return test_params


KNOWN_FAILING_DIRS = {"NIST_NRC_Corner_Effects"}


@pytest.mark.slow
@pytest.mark.local
@pytest.mark.parametrize("input_file,parent_dir,file_prefix", get_test_parameters())
def test_parser_validation(input_file, parent_dir, file_prefix, tmp_path):
    """
    Test parser on validation input files.

    This test:
    1. Parses the input file using parse_cfast_file()
    2. Runs the parsed model
    3. Compares results to reference data generated by CFAST

    Args:
        input_file: Path to the .in file to test
        parent_dir: Parent directory name (e.g., 'WTC')
        file_prefix: File name without extension (e.g., 'WTC_01')
        tmp_path: Pytest temporary directory fixture
    """
    if parent_dir in KNOWN_FAILING_DIRS:
        pytest.skip(
            f"Known bug in {parent_dir} due to Fire class handling table, need to fix"
        )

    reference_data_dir = get_reference_data_dir(
        Path(__file__).parent, "validation_data_local", parent_dir
    )

    try:
        model = parse_cfast_file(input_file)
    except Exception as e:
        pytest.fail(f"Failed to parse {input_file}: {e}")

    model.file_name = str(tmp_path / f"{file_prefix}.in")
    model.cfast_exe = "cfast"
    model.extra_arguments = ["-f"]

    try:
        results = model.run()
        assert isinstance(results, dict), f"Expected dict results, got {type(results)}"
    except Exception as e:
        pytest.fail(f"Failed to run model for {input_file}: {e}")

    try:
        compare_model_to_reference_data(
            results, reference_data_dir, prefix=file_prefix, tmp_path=tmp_path
        )
    except Exception as e:
        pytest.fail(f"Validation comparison failed for {input_file}: {e}")


def test_parser_validation_file_discovery():
    """Test that we can discover validation input files."""
    input_files = get_all_validation_input_files()
    assert len(input_files) > 0, "No validation input files found"

    expected_dirs = {
        "1RFURN",
        "1RWALL",
        "ATF_Corridors",
        "DelCo_Trainers",
        "FM_NBS",
        "FM_SNL",
        "Fleury_Heat_Flux",
        "High_Bay",
        "LLNL_Enclosure",
        "Multi",
        "NBS",
        "NIST_Dunes_2000",
        "NIST_NRC",
        "NIST_NRC_Corner_Effects",
        "NIST_Vent_Study",
        "PRISME",
        "SP_AST",
        "Steckler_Compartment",
        "UL_NFPRF",
        "UL_NIJ_Houses",
        "UL_NIST_Vents",
        "VTT",
        "Vettori_Flat",
        "WTC",
        "iBMB_4",
        "iBMB_5",
    }

    validation_dir = Path(__file__).parent / "Validation"
    found_dirs = set()
    for file_path in input_files:
        parent_path = Path(file_path).parent
        rel_path = os.path.relpath(parent_path, validation_dir)
        found_dirs.add(rel_path)

    missing_dirs = expected_dirs - found_dirs
    if missing_dirs:
        pytest.fail(f"Missing validation directories: {missing_dirs}")


def test_parser_validation_sample():
    """Test parser on a sample validation file to ensure basic functionality."""
    validation_dir = Path(__file__).parent / "Validation" / "WTC"
    sample_file = validation_dir / "WTC_01.in"

    if not sample_file.exists():
        pytest.skip("Sample validation file not found")

    try:
        model = parse_cfast_file(str(sample_file))
        assert model is not None, "Parser returned None"
        assert hasattr(model, "simulation_environment"), (
            "Missing simulation_environment"
        )
        assert hasattr(model, "compartments"), "Missing compartments"
    except Exception as e:
        pytest.fail(f"Failed to parse sample file {sample_file}: {e}")
